name: Firebase Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Debug - List root directory
      run: ls -la

    - name: Deploy to Firebase
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: |
        firebase use --add ${{ secrets.FIREBASE_PROJECT_ID }}
        firebase deploy --only hosting --token $FIREBASE_TOKEN
