name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Ajuste conforme o nome da sua branch principal

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Use Node.js versão 18 ou superior

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}  # Configure este segredo no GitHub Secrets
          PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}  # Configure este segredo no GitHub Secrets
        run: |
          npm install -g firebase-tools
          firebase use --token "$FIREBASE_TOKEN" $PROJECT_ID
          firebase deploy --only hosting --project $PROJECT_ID
